blank_issues_enabled: false
contact_links:
  - name: Community Support Discord (Not Available Yet)
    url: https://github.com/MasterCoder21/PickleUtility/issues/new/choose
    about: Please ask and answer questions here.
