name: Docker Image CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: test the Docker image
        run: make test
